project:
  type: website
  output-dir: docs

website:
  title: "Chlamydia Cody"
  navbar:
    left: 
      - href: research_interests.qmd
        text: Research Interests
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact Info
format:
  html:
    theme: lux
    css: styles.css

editor: visual

